config/routes.rb
Rails.application.routes.draw do

  devise_for :users
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :images

  root to: "posts#home"

  get 'posts/index'
  get 'posts/portfolio', to: 'posts#portfolio'
  get 'posts/:id', to:'posts#show'
  get '/static_pages/:section_name', to:'static_pages#show_section'

  get 'categories/:id', to: 'categories#show'

  resources :posts

  resources :posts do
    resources :comments
  end

  resources "contacts", only: [:new, :create]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

  
    user ||= User.new # guest user (not logged in)
    
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  
  end
end

app/models/bloginfo.rb
class Bloginfo < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :posts

	validates :title, presence: true,
		    length: {minimum: 3}

end

app/models/cms.rb
class Cms < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form from Blog",
      :to => "ggerman@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments

	belongs_to :category
	belongs_to :section

	validates :title, presence: true,
		    length: {minimum: 5}
	has_attached_file :asset, :styles => { :detailed => "1920x1920>", :thumb => "100x100>" }
	validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/
end

app/models/section.rb
class Section < ActiveRecord::Base
	has_many :posts

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/bloginfos_controller.rb
class BloginfosController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
      @posts = Post.page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
  def portfolio
    portfolio_section = Section.find_by(title: 'Portfolio')
    @posts_portfolio = portfolio_section.posts.page(params[:page]) unless portfolio_section.nil?
  end

    def home
      @slider_section = Section.find_by(title: 'Slider')


      @featured_section = Section.find_by(title: 'Featured')


      @portfolio_section = Section.find_by(title: 'Portfolio')

      

    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :asset)
    end


end

app/controllers/user_controller.rb
class UserController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bloginfo(property)
	displayed_property = Bloginfo.where(name: property).first
	unless displayed_property.nil?
		return displayed_property.content
	end
	return 'default'


  end
	def get_categories
		@categories = Category.all
	end

  def links
    return Bloginfo.where(name: 'links').all
  end
end

app/helpers/bloginfos_helper.rb
module BloginfosHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/contacts/create.html.erb
<h1>Thank you for your message.</h1>
<p>We'll get back to you soon.</p>

app/views/contacts/new.html.erb
<div class="row">
	<div class="col-sm-4">
		<h3>Drop me a line!</h3>
		<hr>
		<address>
		<strong>Email:</strong> <a href="mailto:#"> name@domain.com</a><br><br>
		<strong>Phone:</strong> (555)123-4567
		</address>
	</div>

	<div class="col-sm-8 contact-form">
		<%= simple_form_for @contact, :html => {:class => 'contact' } do |f| %>
	<div class="row">


	<div class="col-xs-6 col-md-6 form-group">
		<%= f.text_field :name, :required => true, :class => 'form-control', :placeholder => 'Your Name' %>
	</div>
	<div class="col-xs-6 col-md-6 form-group">
		<%= f.text_field :email, :required => true, :class => 'form-control', :placeholder => 'Your Email' %>
	</div>
</div>
	<%= f.text_area :message, :as => :text, :required => false, :input_html => {:rows => 10}, :class => 'form-control', :placeholder => 'Your Message' %>
	<br />
	<div class="row">
		<div class="col-xs-12 col-md-12 form-group">
		<%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
		<% end %>
		</div>
</div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <br />
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :class => 'ckeditor' %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<br />

app/views/posts/edit.html.erb
<%= javascript_include_tag "ckeditor/ckeditor.js" %>

<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/posts/home.html.erb
<% unless @slider_section.nil?  %>
    <!-- Header Carousel -->
    <header id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">

		<% for @post in @slider_section.posts %>
            <div class="item active">
                <div class="fill" style="background-image:url('<%= root_url + @post.asset.url %>');"></div>
                <div class="carousel-caption">
                    <h2><%= @post.title %> </h2>
                </div>
            </div>
		<% end %>

        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </header>
<% end %>
    <!-- Page Content -->


        <!-- Marketing Icons Section -->
        <div class="row" id="featured" >

            <% unless @featured_section.nil?  %>

            <% for @post in @featured_section.posts %>
            <div class="col-md-4 col-centered">


                        <h3><i class="fa fa-fw fa-check"></i> <%= @post.title %></h3>
			<div class="featured-content">
                        	<p><%= truncate( @post.content, length: 260, escape: false) %></p>
			</div>
                        <a href="/posts/<%= @post.id  %>" class="btn-sm btn-default">Learn More</a>
            </div>
            <% end %>
	    <% end %>
        </div>
        <!-- /.row -->

        <!-- Portfolio Section -->
	<% unless @portfolio_section.nil? %>
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Our Work</h2>
            </div>

	    <% @portfolio_section.posts.each do |post| %>
            <div class="col-md-4 col-sm-6">
                <a href="<%= post_path post %>">
                    <img class="img-responsive img-portfolio img-hover" src="<%= post.asset.url %>" alt="">
                </a>
            </div>
	    <% end %>

        </div>
	<% end %>
        <!-- /.row -->

    

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

app/views/posts/index.html.erb
  <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    Blog
                    <small>Our latest posts</small>
                </h1>
    <% @posts.each do |post| %>
                <!-- First Blog Post -->
                <h2>
                    <%= link_to post.title, post %>
                </h2>
                <p class="lead">
                    by <a href="index.php">Start Bootstrap</a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> <%= post.updated_at %></p>
                <hr>
                <img class="img-responsive" src="<%= root_url + post.asset.url %>" alt="">
                <hr>
                <p><%= post.content[0, 200].gsub('<strong>', '').html_safe %>... <%= link_to '[More Info]', post %></p>

		<%= link_to 'Read More', post_path(post), class: 'btn btn-primary'  %>

                <hr>

    <% end %>

                <!-- Pager -->
<%= paginate @posts %>
            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">



                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-12">

                            <ul class="list-unstyled">
				<% for @category in get_categories %>
                                <li><a href="#"><%=  @category.title %></a>
                                <% end %>
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->

                        <!-- /.col-lg-6 -->
                    </div>
                    <!-- /.row -->
                </div>

            </div>

        </div>
        <!-- /.row -->

app/views/posts/new.html.erb
<%= javascript_include_tag "ckeditor/ckeditor.js" %>

<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/posts/portfolio.html.erb
  <div class="row">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Portfolio
                    <small><%= @posts_portfolio.count %> items</small>
                </h1>
            </div>

        </div>
        <!-- /.row -->

    <% for @post in @posts_portfolio %>
        <!-- /.row -->

        <div class="row">
            <div class="col-md-7">
                <a href="#">
                    <img class="img-responsive" src="<%= root_url + @post.asset.url %>" alt="">
                </a>
            </div>
            <div class="col-md-5">
                <h3><%= @post.title %></h3>
                <p><%=  @post.content.html_safe %></p>
		<%= link_to 'See More', post_path(@post), class: 'btn btn-primary'  %>

            </div>
        </div>
        <!-- /.row -->        
	<hr>

    <% end %>

                <!-- Pager -->
<%= paginate @posts_portfolio %>

            </div>

app/views/posts/show.html.erb
        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!-- Blog Post -->

                <!-- Title -->
                <h1><%= @post.title %></h1>

                <!-- Author -->
                <p class="lead">
                    by <a href="#">Start Bootstrap</a>
                </p>

                <hr>

                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span> Posted on <%= @post.created_at.to_formatted_s :long %></p>

                <hr>

                <!-- Preview Image -->
                <img class="img-responsive" src=".it/900x300" alt="">

                <hr>

                <!-- Post Content -->
                 <%= @post.content.html_safe %>

                <hr>

                <!-- Blog Comments -->

                <!-- Comments Form -->
                <div class="well">
                <h4>Leave a Comment:</h4>
                               <div class="form-group">
					  <%= form_for([@post, @post.comments.build]) do |f| %>
			    <p>
			      <%= f.label :commenter %><br>
			      <%= f.text_field :commenter, :class => 'form-control' %>
			    </p>
			    <p>
			      <%= f.label :body %><br>
			      <%= f.text_area :body, :class => 'form-control'  %>
			    </p>
			    <p>
			      <%= f.submit :send, :class => 'btn btn-primary'%>
			    </p>
			  <% end %>

			</div>
		</div>
                <hr>

                <!-- Posted Comments -->

                <!-- Comment -->

			<% @post.comments.each do |comment| %>
			<% unless comment.nil? %>
			<div class="media">

			    <div class="media-body">
				<h4 class="media-heading"><%= comment.commenter %>
				    <small><%= comment.created_at %></small>
				</h4>
				<%= comment.body %>
			    </div>
			</div>
			<% end %>
			<% end %>

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">


                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-12">

                            <ul class="list-unstyled">
				<% for @category in get_categories %>
                                <li><a href="#"><%=  @category.title %></a>
                                <% end %>
                            </ul>
                        </div>

                    </div>
                    <!-- /.row -->
                </div>



            </div>

        </div>





<%
=begin
\<\%\= link_to 'Edit', edit_post_path(@post) \%\> |
\<\%\= link_to 'Back', posts_path \%\>
=end
%>