config/routes.rb
Rails.application.routes.draw do

  devise_for :users
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :images

  root to: "posts#home"

  get 'posts/index'
  get 'posts/portfolio', to: 'posts#portfolio'
  get 'posts/:id', to:'posts#show'
  get '/static_pages/:section_name', to:'static_pages#show_section'

  get 'categories/:id', to: 'categories#show'

  resources :posts

  resources :posts do
    resources :comments
  end

  resources "contacts", only: [:new, :create]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

  
    user ||= User.new # guest user (not logged in)
    
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  
  end
end

app/models/bloginfo.rb
class Bloginfo < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :posts

	validates :title, presence: true,
		    length: {minimum: 3}

end

app/models/cms.rb
class Cms < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form from Blog",
      :to => "ggerman@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments

	belongs_to :category
	belongs_to :section

	validates :title, presence: true,
		    length: {minimum: 5}
	has_attached_file :asset, :styles => { :detailed => "1920x1920>", :thumb => "100x100>" }
	validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/
end

app/models/section.rb
class Section < ActiveRecord::Base
	has_many :posts

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
      @posts = Post.page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
  def portfolio
    portfolio_section = Section.find_by(title: 'Portfolio')
    @posts_portfolio = portfolio_section.posts.page(params[:page]) unless portfolio_section.nil?
  end

    def home
      @slider_section = Section.find_by(title: 'Slider')


      @featured_section = Section.find_by(title: 'Featured')


      @portfolio_section = Section.find_by(title: 'Portfolio')

      

    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :asset)
    end


end

app/controllers/user_controller.rb
class UserController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bloginfo(property)
	displayed_property = Bloginfo.where(name: property).first
	unless displayed_property.nil?
		return displayed_property.content
	end
	return 'default'


  end
	def get_categories
		@categories = Category.all
	end

  def links
    return Bloginfo.where(name: 'links').all
  end
end

app/helpers/bloginfos_helper.rb
module BloginfosHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/friends/german.html.erb
<h1>Friends#german</h1>
<p>Find me in app/views/friends/german.html.erb</p>

app/views/friends/testing.html.erb
<%= @text %>

app/views/friends/tiziano.html.erb
<h1>Friends#tiziano</h1>
<p>Find me in app/views/friends/tiziano.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= bloginfo :title %></title>
  <meta name="keywords" content="<%= bloginfo :keywords %>"/>
  <meta name="description" content="<%= bloginfo :description %>"/>

  <link href='http://fonts.googleapis.com/css?family=Coda+Caption:800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag :application, :media => "all" %>

  <%= stylesheet_link_tag 'rambling.slider' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= favicon_link_tag 'favicon.jpg' %>


  <%= csrf_meta_tags %>

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body>
	    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/" title="<%= bloginfo :title %>"><%= image_tag "logo.png" %></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/cms/about">About</a>
                    </li>
                    <li>
                        <a href="/cms/services">Services</a>
                    </li>
                    <li>
                        <a href="/contacts/new">Contact</a>
                    </li>
                    <li class="dropdown">
                         <a href="/posts/portfolio">Portfolio</a>
                    </li>
                    <li class="dropdown">
                        <a href="/posts/" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
                        <ul class="dropdown-menu">
				<% for @category in get_categories %>
					    <li>
						<a href="/categories/<%= @category.id %>"><%= @category.title %></a>
					    </li>
				<% end %>
					<li>
						<a href="/posts/">All Posts</a>
					    </li>
                        </ul>
                    </li>

                    <%  if user_signed_in? %>
			<li><a href="/admin">Logged in as <%= current_user.email %></a></li>
			<% else %>
					<li class="dropdown" id="login-menu">
						<a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign In <strong class="caret"></strong></a>
						<div class="dropdown-menu" style="padding: 15px;">
							<label>Please login:</label>
							<%= form_for(:user, :url => session_path(:user)) do |f| %>
							  <%= f.text_field :email,  {:class => 'form-control', :placeholder => 'Email' } %>
							  <%= f.password_field :password,  {:class => 'form-control', :placeholder => 'Password' } %>
							  <%= f.check_box :remember_me %>
							  <%= f.label :remember_me %>
							  <%= f.submit 'Sign in',  :class => 'form-control  btn-small btn-primary' %>
							  <%= link_to "Forgot your password?", new_password_path(:user) %>
							<% end %>
						</div>
					</li>


			<% end %>
                </ul>





            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <div class="container">
	<%= yield %>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
<hr />
                    <p>Copyright &copy; EosWeb 2014</p>
                </div>
            </div>
        </footer>

	    </div>
</body>
</html>